# Generated by Django 5.1.2 on 2025-01-28 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.category'),
        ),
    ]
