# Generated by Django 5.1.2 on 2025-01-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_sub_category_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app1.category'),
        ),
    ]
