# Generated by Django 5.1.3 on 2025-02-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_userinfomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='signinModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
    ]
