# Generated by Django 5.1.3 on 2025-02-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_signinmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signinmodel',
            name='email',
        ),
        migrations.AddField(
            model_name='signinmodel',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signinmodel',
            name='password',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
