# Generated by Django 5.1.3 on 2025-01-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecitypage',
            name='city_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
