# Generated by Django 5.1.3 on 2025-02-01 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_packagedetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PackageDetail',
        ),
    ]
