# Generated by Django 5.1.3 on 2025-02-04 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_package_details_category_package_details_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package_details_category',
            old_name='day1',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='package_details_category',
            name='day2',
        ),
        migrations.RemoveField(
            model_name='package_details_category',
            name='day3',
        ),
        migrations.RemoveField(
            model_name='package_details_category',
            name='day4',
        ),
        migrations.RemoveField(
            model_name='package_details_category',
            name='day5',
        ),
    ]
