# Generated by Django 5.1.2 on 2025-02-09 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_day1_package_details_category_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.sub_category'),
            preserve_default=False,
        ),
    ]
