# Generated by Django 5.1.2 on 2025-02-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_feedback_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='cid',
        ),
    ]
