# Generated by Django 5.1.2 on 2025-02-10 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_feedback_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='package_details_category',
            name='package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.basecitypage'),
        ),
    ]
